### ISSUE TITLE
Speed of stringify causing tests to timeout

### ISSUE THREAD

**Issue by spalger** [kjbekkelund/expect-to#1]
I was shocked that this was the case, but it seems that the `stringify()` function is so slow that it can cause tests with mocha's standard 2second timeout to fail. The unfortunate part is that these tests wouldn't fail otherwise (and therefore didn't even need the stringified values they worked so hard to create).

Switching to the [`util.inspect()`](https://nodejs.org/api/util.html#util_util_inspect_object_options) function in the stdlib seemed to be perfectly performant, but it also limits how deeply it will recurse into an object.

The objects being stringified in this case were jsdom nodes as part of an `equal()` test.

**Comment by spalger** [comment]
More interesting results: if I replace stringify with:

```js
module.exports = function (val) {
  return require('util').inspect(val, { depth: 10, colors: true });
};
```

The test will take a while longer (around 150ms) but if I increase the depth to 20 the test fails.

**Comment by kjbekkelund** [comment]
Haha, interesting. It's basically a pure copy from mocha. I'll look at changing this. I've been a bit frustrated with the output either way.
